trigger:
  - main
pool:
  Name: 'Filecopy'
 
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet
 
- task: DotNetCoreCLI@2
  displayName: 'Restore dependencies'
  inputs:
    command: 'restore'
    projects: '$(Build.SourcesDirectory)/ConsoleApp12/ConsoleApp12.csproj'
 
- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/ConsoleApp12/ConsoleApp12.csproj'
 
- task: DotNetCoreCLI@2
  displayName: 'Publish project'
 
  inputs:
    command: 'publish'
    projects: '$(Build.SourcesDirectory)/ConsoleApp12/ConsoleApp12.csproj'
    publishWebProjects: false
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/publish'
 
- powershell: |
    Write-Host "Creating zip file..."
    $publishFolder = "$(Build.ArtifactStagingDirectory)/publish"
    $zipFile = "$(Build.ArtifactStagingDirectory)/myArtifact.zip"
    Compress-Archive -Path $publishFolder\* -DestinationPath $zipFile
  displayName: 'Create .zip file using PowerShell'
 
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'  
    targetFolder: '$(Build.ArtifactStagingDirectory)'  
 
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
 
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  
    ArtifactName: 'drop'
    publishLocation: 'Container'
 
- task: AzureFileCopy@6
  displayName: 'Upload Artifact to Azure Blob'
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/*.zip'  
    azureSubscription: 'Devops-service-con' 
    Destination: 'AzureBlob'  
    storage: 'teststorageaccten'  
    ContainerName: 'venkattest'